modLoader = "javafml"
loaderVersion = "[${forge_loader_version},)"
license = "MIT"
issueTrackerURL = "https://github.com/LukenSkyne/Minecraft-Ping-Wheel/issues"

[[mods]]
modId = "pingwheel"
version = "${version}"
displayName = "Ping Wheel"
displayURL = "https://github.com/LukenSkyne/Minecraft-Ping-Wheel"
logoFile = "icon.png"
authors = "Luken, RXJpaw"
description = '''
Mark locations similar to the ping mechanism found in modern co-op multiplayer games.
'''

[[dependencies.pingwheel]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pingwheel]]
modId = "minecraft"
mandatory = true
versionRange = "${forge_compatible_range}"
ordering = "NONE"
side = "BOTH"
