modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL = "https://github.com/LukenSkyne/Minecraft-Ping-Wheel/issues"

[[mods]]
modId = "pingwheel"
version = "${version}"
displayName = "Ping Wheel"
logoFile = "icon.png"
description = '''
Mark locations similar to the ping mechanism found in modern co-op multiplayer games.
'''

[[dependencies.pingwheel]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pingwheel]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "NONE"
side = "BOTH"
