name: "Forge Release"

on: workflow_dispatch

jobs:
  release:
    uses: ./.github/workflows/platform-release.yml
    with:
      loader: forge
    secrets:
      MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}
      CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
