name: "Platform Release"

on:
  workflow_call:
    inputs:
      loader:
        required: true
        description: the loader name, can be "fabric" or "forge"
        type: string
    secrets:
      MODRINTH_API_TOKEN:
        required: true
      CURSEFORGE_API_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"

      - name: "Build with Gradle"
        id: build
        run: chmod +x gradlew && ./gradlew :${{ inputs.loader }}:build

      - name: "Archive build artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ./${{ inputs.loader }}/build/libs
            CHANGELOG.md
            gradle.properties

  publish:
    runs-on: ubuntu-latest
    environment: "release"
    needs: [build]
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2

      - name: "Download build artifacts"
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: "Extract gradle properties"
        run: |
          echo "ARCHIVE_NAME=$(grep "archives_base_name=" gradle.properties | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "MOD_VERSION=$(grep "mod_version=" gradle.properties | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "MC_VERSION=$(grep "minecraft_version=" gradle.properties | cut -d "=" -f 2)" >> $GITHUB_ENV

      - name: "Set release info"
        run: |
          LOADER_NAME=$(echo ${{ inputs.loader }} | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
          echo "RELEASE_NAME=v${{ env.MOD_VERSION }} for $LOADER_NAME ${{ env.MC_VERSION }}" >> $GITHUB_ENV
          echo "TAG_NAME=v${{ env.MOD_VERSION }}-${{ inputs.loader }}-${{ env.MC_VERSION }}" >> $GITHUB_ENV

      - name: "Move output to build directory"
        run: |
          mkdir -p ./build/libs
          mv ./${{ inputs.loader }}/build/libs/${{ env.ARCHIVE_NAME }}-${{ env.MOD_VERSION }}.jar ./build/libs/${{ env.ARCHIVE_NAME }}-${{ env.MOD_VERSION }}-${{ inputs.loader }}-${{ env.MC_VERSION }}.jar

      - name: "Create version tag"
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: "Publish to Platforms"
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: QQXAdCzh
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          curseforge-id: 734339
          curseforge-token: ${{ secrets.CURSEFORGE_API_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ env.TAG_NAME }}
          github-prerelease: false

          name: ${{ env.RELEASE_NAME }}
          changelog-file: CHANGELOG.md

          loaders: |
            ${{ inputs.loader }}
          game-versions: |
            >=1.18 <=1.18.2

          # only needed for the 'fabric' loader, so we conditionally inject it
          dependencies: ${{ inputs.loader == 'fabric' && 'fabric-api(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)' || '' }}

          # forge releases are marked as beta for easier visual distinction
          version-type: ${{ inputs.loader == 'forge' && 'beta' || '' }}

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
